// <auto-generated />
namespace darktierstudios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class projectslug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(projectslug));
        
        string IMigrationMetadata.Id
        {
            get { return "201710181509348_project-slug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
